#!/bin/bash
set -Eeo pipefail

# shellcheck disable=2154
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

reArgsMaybe="^[^:[:space:]]+:.*$" # Smallest indication of attempt to use argument
reArgSkip='^([[:blank:]]*#.*|[[:blank:]]*)$' # comment or empty line

# Paths
acipersistPath="/home/file2blob/share"
aciUserConf="$acipersistPath/users.conf"
aciHostkeysPath="$acipersistPath/hostkeys"
aciSshdConfig="$acipersistPath/sshd_config"
userConfPath="/etc/sftp/users.conf"
userConfPathLegacy="/etc/sftp-users.conf"
userConfFinalPath="/var/run/sftp/users.conf"


function log() {
    echo "[$(date)][$0] $*" >&2
}

# Allow running other programs, e.g. bash
if [[ -z "$1" || "$1" =~ $reArgsMaybe ]]; then
    startSshd=true
else
    startSshd=false
fi

# Backward compatibility with legacy config path
if [ ! -f "$userConfPath" ] && [ -f "$userConfPathLegacy" ]; then
    log "found legacy config path at $userConfPathLegacy"
    mkdir -p "$(dirname $userConfPath)"
    ln -s "$userConfPathLegacy" "$userConfPath"
    log "linked legacy config path to $userConfPath"
fi

# Create users only on first run
if [[ ! -f "$userConfFinalPath" ]]; then
    mkdir -p "$(dirname $userConfFinalPath)"
    log "Looks like firstrun, created $userConfFinalPath"

    if [ -f "$userConfPath" ]; then
        log "found $userConfPath, appending users to $userConfFinalPath"
        # Append mounted config to final config
        grep -v -E "$reArgSkip" < "$userConfPath" > "$userConfFinalPath"
    fi

    if [[ -f "$aciUserConf" ]]; then
        log "found $aciUserConf, adding to $userConfFinalPath"
        # Append mounted config to final config
        grep -v -E "$reArgSkip" < "$aciUserConf" > "$userConfFinalPath"
    fi

    if $startSshd; then
        # Append users from arguments to final config
        for user in "$@"; do
            echo "$user" >> "$userConfFinalPath"
        done
    fi

    if [[ -n "$SFTP_USERS" ]]; then
        # Append users from environment variable to final config
        IFS=" " read -r -a usersFromEnv <<< "$SFTP_USERS"
        for user in "${usersFromEnv[@]}"; do
            echo "$user" >> "$userConfFinalPath"
        done
    fi

    # Check that we have users in config
    if [[ -f "$userConfFinalPath" ]] && [[ "$(wc -l < "$userConfFinalPath")" -gt 0 ]]; then
        # Import users from final conf file
        while IFS= read -r user || [[ -n "$user" ]]; do
            create-sftp-user "$user"
        done < "$userConfFinalPath"
    elif $startSshd; then
        log "FATAL: No users provided!"
        exit 3
    fi
    
    aciHostkeysPath="$acipersistPath/hostkeys"
    if [ -e "$aciHostkeysPath" ] ; then
        # for f in "$(cd $aciHostkeysPath && ls *_key)"; do
        #     log "line 85: found $f"
        #     acihostkey="$f"
        #     hostkey="/etc/ssh/$f"
        #     cp -f "$f" /etc/ssh/
        # done
        # for f in /etc/ssh/*_key; do
            cp $aciHostkeysPath/*_key /etc/ssh/
            chown root:root /etc/ssh/*_key
            chmod 600 /etc/ssh/*_key
            log "copied and owned keys in $aciHostkeysPath"
        # done        
        # chown -R root:root /etc/ssh
        # chmod 600 /etc/ssh/*_key
        # log "owned all keys in /etc/ssh/*_key"
        # unset key
        # unset acihostkey
        # unset hostkey
    else
        log "couldn't find $aciHostkeysPath"
    fi

    if [ ! -e "$aciHostkeysPath" ]; then
        mkdir -p "$aciHostkeysPath"
        log "created $aciHostkeysPath"
    fi

    if [ ! -f /etc/ssh/ssh_host_ed25519_key ] ; then
        log "couldnt find /etc/ssh/ssh_host_ed25519_key"
        ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N '' -E md5
        if [ ! -e "$aciHostkeysPath/ssh_host_ed25519_key" ]; then
            cp /etc/ssh/ssh_host_ed25519_key "$aciHostkeysPath"/ssh_host_ed25519_key
        fi
    fi

    if [ ! -f /etc/ssh/ssh_host_rsa_key ]; then
        log "couldnt find /etc/ssh/ssh_host_rsa_key"
        ssh-keygen -t rsa -b 2048 -f /etc/ssh/ssh_host_rsa_key -N '' -E md5
        if [ ! -e "$aciHostkeysPath"/ssh_host_rsa_key ]; then
            cat /etc/ssh/ssh_host_rsa_key > "$aciHostkeysPath"/ssh_host_rsa_key
        fi
    fi

fi


# Source custom scripts, if any
aciScriptPath="$acipersistPath/scripts"
if [[ -d "$aciScriptPath" ]]; then
    for f in "$aciScriptPath"/*.sh ; do
        if [[ -x "$f" ]]; then
            log "Running $f ..."
            $f
        else
            log "Could not run $f, because it's missing execute permission (+x)."
        fi
    done
    unset f
fi


# copy sshd_config from /acipersist if exists, if doesnt exist copy it from /etc/ssh
if [[ -f "$aciSshdConfig" ]] && [[ ! "$aciSshdConfig" -ef /etc/ssh/sshd_config ]] ; then
    rm /etc/ssh/sshd_config
    cp "$aciSshdConfig" /etc/ssh/sshd_config
    log "copied sshd_config from $aciSshdConfig"
elif [[ -e "$acipersistPath" ]] &&  [[ ! -f "$aciSshdConfig" ]]; then
    cp /etc/ssh/sshd_config "$aciSshdConfig"
    log "copied sshd defaultconfig to $aciSshdConfig"
fi

# Generate public keys for this container
for f in /etc/ssh/*_key; do
    ssh-keygen -y -f "$f" > "$f".pub
    log "generated $f.pub"
done

if $startSshd; then
    log "Executing sshd"
    exec /usr/sbin/sshd -D -e
else
    log "Executing $*"
    exec "$@"
fi
