#!/bin/bash
set -Eeo pipefail

# shellcheck disable=2154
trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

reArgsMaybe="^[^:[:space:]]+:.*$" # Smallest indication of attempt to use argument
reArgSkip='^([[:blank:]]*#.*|[[:blank:]]*)$' # comment or empty line

# Paths
acipersistPath="/acipersist"
aciUserConf="$acipersistPath/users.conf"
aciHostkeysPath="$acipersistPath/hostkeys"
aciSshdConfig="$acipersistPath/sshd_config"
userConfPath="/etc/sftp/users.conf"
userConfPathLegacy="/etc/sftp-users.conf"
userConfFinalPath="/var/run/sftp/users.conf"


function log() {
    echo "[$(date)][$0] $*" >&2
}

# Allow running other programs, e.g. bash
if [[ -z "$1" || "$1" =~ $reArgsMaybe ]]; then
    startSshd=true
else
    startSshd=false
fi

# Backward compatibility with legacy config path
if [ ! -f "$userConfPath" ] && [ -f "$userConfPathLegacy" ]; then
    log "found legacy config path at $userConfPathLegacy"
    mkdir -p "$(dirname $userConfPath)"
    ln -s "$userConfPathLegacy" "$userConfPath"
    log "linked legacy config path to $userConfPath"
fi

# Create users only on first run
if [[ ! -f "$userConfFinalPath" ]]; then
    mkdir -p "$(dirname $userConfFinalPath)"
    log "Looks like firstrun, created $userConfFinalPath"

    if [ -f "$userConfPath" ]; then
        log "found $userConfPath, appending users to $userConfFinalPath"
        # Append mounted config to final config
        grep -v -E "$reArgSkip" < "$userConfPath" > "$userConfFinalPath"
    fi

    if [[ -f "$aciUserConf" ]]; then
        log "found $aciUserConf, adding to $userConfFinalPath"
        # Append mounted config to final config
        grep -v -E "$reArgSkip" < "$aciUserConf" > "$userConfFinalPath"
    fi

    if $startSshd; then
        # Append users from arguments to final config
        for user in "$@"; do
            echo "$user" >> "$userConfFinalPath"
        done

        # copy SSHD Config from /acipersist if exists, if doesnt exist create it from git's defaultconfig
        if [ -f "$aciSshdConfig" ] ; then
            rm /etc/ssh/sshd_config
            cp "$aciSshdConfig" /etc/ssh/sshd_config
            log "copied sshd_config from $aciSshdConfig"
        elif [ ! -f "$aciSshdConfig" ] && [ -d "$acipersistPath" ] ; then
            cp /etc/ssh/sshd_config "$aciSshdConfig"
            log "copied sshd defaultconfig to $aciSshdConfig"
        fi

    fi

    if [[ -n "$SFTP_USERS" ]]; then
        # Append users from environment variable to final config
        IFS=" " read -r -a usersFromEnv <<< "$SFTP_USERS"
        for user in "${usersFromEnv[@]}"; do
            echo "$user" >> "$userConfFinalPath"
        done
    fi

    # Check that we have users in config
    if [[ -f "$userConfFinalPath" ]] && [[ "$(wc -l < "$userConfFinalPath")" -gt 0 ]]; then
        # Import users from final conf file
        while IFS= read -r user || [[ -n "$user" ]]; do
            "create-sftp-user" "$user"
        done < "$userConfFinalPath"
    elif $startSshd; then
        log "FATAL: No users provided!"
        exit 3
    fi

    # Generate unique ssh keys for this container, if needed

    if [ ! -d $aciHostkeysPath ] ; then
        mkdir -p $aciHostkeysPath && log "created $aciHostkeysPath"
    fi

    # pubkeys=$(echo "$(ls /etc/ssh | grep _key.pub)")
    # for key in $pubkeys; do
    #         rm /etc/ssh/$key
    #         log removedd $key
    # done

    if [ ! -z "$(ls $aciHostkeysPath/ssh_host_*_key)" ] ; then
        hostkeys="$(ls $aciHostkeysPath | grep _key)"
        if [[ $hostkeys != *.pub ]] ; then
            for key in $hostkeys; do
                log "found $key"
                cat $aciHostkeysPath/$key > /etc/ssh/$key < /dev/null
                chown 0:0 "/etc/ssh/$key"
                chmod 600 "/etc/ssh/$key"
                log "copied $key from $aciHostkeysPath to /etc/ssh"
                if [ -f "/etc/ssh/$key.pub" ] ; then
                    rm "/etc/ssh/$key.pub"
                    log "removed /etc/ssh/$key.pub"
                fi
                ssh-keygen -y -f /etc/ssh/$key > /etc/ssh/$key.pub < /dev/null
                log $(ssh-keygen -l -E md5 -f /etc/ssh/$key.pub)
            done
        fi
    fi

    if [ ! -d /etc/ssh ]; then
        mkdir -p /etc/ssh && log "created /etc/ssh"
    fi
    
    if [ ! -f /etc/ssh/ssh_host_ed25519_key ]; then
        log "couldnt find /etc/ssh/ssh_host_ed25519_key"
        ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N '' -E md5
        cat /etc/ssh/ssh_host_ed25519_key > "$aciHostkeysPath/ssh_host_ed25519_key" < /dev/null
    fi
    if [ ! -f /etc/ssh/ssh_host_rsa_key ]; then
        log "couldnt find /etc/ssh/ssh_host_rsa_key"
        ssh-keygen -t rsa -b 2048 -f /etc/ssh/ssh_host_rsa_key -N '' -E md5
        cat /etc/ssh/ssh_host_rsa_key > "$aciHostkeysPath/ssh_host_rsa_key" < /dev/null
    fi
fi

# Source custom scripts, if any
if [[ -d $acipersistPath/scripts ]]; then
    for f in $acipersistPath/scripts/*.sh ; do
        if [[ -x "$f" ]]; then
            log "Running $f ..."
            $f
        else
            log "Could not run $f, because it's missing execute permission (+x)."
        fi
    done
    unset f
fi

if $startSshd; then
    log "Executing sshd"
    exec /usr/sbin/sshd -D -e
else
    log "Executing $*"
    exec "$@"
fi
